name: figma_plugin
description: The figma plugin to generate Flutter code.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  figma_codegen:
    path: ../../packages/figma_codegen/

dev_dependencies:
  lints: ^4.0.0
