name: binui
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  archive: ^4.0.4
  dart_style: ^3.1.3
  path: ^1.9.0
  protobuf: ^6.0.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  orbe_proto: ^0.1.5
  test: ^1.25.6
