name: figma_codegen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  orbe_proto: ^0.1.5
dependencies:
  recase: ^4.1.0
