name: figma_codegen
description: Code generation tools for Figma designs. Generate Flutter widgets and styles from Figma files.
version: 0.1.2
repository: https://github.com/aloisdeniel/flutter_figma

environment:
  sdk: ^3.10.4

dependencies:
  recase: ^4.1.0
  args: ^2.5.0
  protobuf: ^6.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  orbe_proto: ^0.1.5

executables:
  figma_codegen:
